@startuml Actores

left to right direction

actor Tecnico
actor "Exchange Online" as Exchange
actor "Microsoft Forms" as Forms

note right of Tecnico
**Técnico**:
Consulta los formularios pendientes,
gestiona las solicitudes y actualiza su estado
end note

note right of Exchange
**Exchange Online**:
Servicio de correo que genera eventos
cuando se recibe un nuevo mensaje
end note

note right of Forms
**Microsoft Forms**:
Servicio de formularios que genera eventos
cuando un formulario es completado
end note

@enduml