@startuml Flujo_Formulario

top to bottom direction

[*] --> Recibido : CA2 Recibir formulario

Recibido --> Evaluar_Documentacion : Sistema analiza campo de documentación

Evaluar_Documentacion --> Enviar_Instrucciones : Opción documentación marcada
Evaluar_Documentacion --> Procesar_Datos : No marcada

Enviar_Instrucciones --> Procesar_Datos : Sistema envía correo con instrucciones

Procesar_Datos --> Guardado_BBDD : Sistema procesa y guarda datos

Guardado_BBDD --> [*]

@enduml