@startuml Tecnico

hide empty description

[*] --> EsperandoCorreo

EsperandoCorreo --> CorreoRecibido : llega correo
CorreoRecibido --> AnalizandoCorreo

AnalizandoCorreo --> InterpretandoIntencion

InterpretandoIntencion --> EvaluarSolicitud

EvaluarSolicitud --> SinConsulta : no requiere datos
EvaluarSolicitud --> ConsultandoSistemas : requiere datos

ConsultandoSistemas --> ConsultaSgipe
ConsultaSgipe --> ConsultaPetter
ConsultaPetter --> ConsultaWepes

ConsultaWepes --> AnalisisDatos

SinConsulta --> GenerandoRespuesta
AnalisisDatos --> GenerandoRespuesta

GenerandoRespuesta --> EnviandoRespuesta
EnviandoRespuesta --> [*]

@enduml
