@startuml
left to right direction

actor ResponsableProducción

package "VT" {
 
  usecase "CU-02 Listar partición" as CU02
  usecase "CU-01 Listar particiones" as CU01

}


ResponsableProducción --> CU01
ResponsableProducción --> CU02


@enduml